### ISSUE TITLE
Allow authors to "post" new version

### ISSUE THREAD

**Issue by arcaldwell49** [lepidus/authorVersion#2]
Wonderful job on this plugin, it has been very helpful for the preprint server I manage. However, while users can create a new version, they cannot post it. I think that may be a useful feature for some if they want to screen the updated versions. However, we just want to review the initial submission but allow authors to have the freedom to update from that point onward. 

So, would it be possible to update the plugin to allow for authors to create and post new versions?

**Comment by devinberg** [comment]
This feature would be great as long as it is optional. I would like to retain the ability to screen/approve revisions.

**Comment by diegoabadan** [comment]
Oops, just now I noticed this issue.

We are happy to hear that you are using the plugin.

The development of this plugin has been to meet the needs of [Scielo Preprints](https://preprints.scielo.org/index.php/scielo)

We would be happy to receive a code collaboration that makes this configurable. Alternatively, we can also work with sponsored development to implement additional features that Scielo wants or can prioritize at the moment.

I am also forwarding this request to the Scielo team to evaluate it.
