### ISSUE TITLE
Allow authors to submit their new version

### ISSUE THREAD

**Issue by devinberg** [lepidus/authorVersion#3]
Related to, but different from, #2. 

It would be useful if authors could "Submit" their new version of the preprint for moderation using the same workflow used for submitting a new preprint. As it stands now, they must separately contact a moderator to notify them that they have created a new version and that it is ready to post.

**Comment by devinberg** [comment]
@diegoabadan @JhonathanLepidus what might sponsored development of this feature look like?

**Comment by JhonathanLepidus** [comment]
Greetings @devinberg

We are currently reviewing your proposal to identify what solution to provide. To that end, we would like to ask you a few questions.

First, what version of OPS are you currently using? Would the solution to be implemented be for this same version?

In OPS there is a notification that is sent to moderators when a new version of a submission is created.
However, I believe that the difficulty is knowing when the author has finished the modifications and the submission can be posted, right?

If not, can you detail what the expected flow would be like?

Please, let us know of any other issues.

**Comment by devinberg** [comment]
@JhonathanLepidus 

I am on version 3.3.0.13. My site is hosted by PKP|PN so updates are managed by them. I don't exactly know what their upgrade schedule looks like for hosted services, but I would like for the plugin to work for whichever version I am on.

Yes, an email notification is sent when a new version is created. However, as a preprint manager I cannot act on this notification because I don't know when the user is finished making their edits, as you said. You can see my current [preprint editing workflow here](https://engrxiv.org/submission-editing), however, many users miss this page and thus do not notify me when their new version is ready to post.

My desired workflow would provide users with a button to "Submit new version" which would then place it in my normal Submissions workflow with some indication that it is a new version rather than a new submission.

**Comment by diegoabadan** [comment]
Thanks @devinberg  for the information.

Next Tuesday we have a meeting with the Scielo team. We will talk to them about your request and get back to you, ok?

If this feature is also a desire of Scielo, it will be easier to keep the plugin working well for you and Scielo.

**Comment by diegoabadan** [comment]
@devinberg , we spoke to the SciELO team last week, and they would be happy to have this feature in the plugin.

Below we describe how this feature could serve both of them. Please see if you agree.

**Note:** we are concerned here with functionality, details such as some terms and minor adjustments may be made during development or after the initial version is delivered.

**Author's view**

When creating a new version, we will add to the current OPS new version page a "reason" text field, which is mandatory to fill in, and a "Submit new version" button.  When clicking on this button, there may be a confirmation window indicating that the new version will be sent for moderation, for example.

After writing the reason and submitting the request, an email notification will be sent to the moderators assigned to this submission informing them that the new version is ready to be reviewed and posted.

**Moderators view**

On the submissions page there will be a new tab called "New versions". It will list the submissions that have new versions that are waiting to be posted.

When accessing a submission that has a new version ready for posting, it will be possible to view the reason informed by the author.

**Public view of the new version**
After the new version is posted, the reason will also be displayed on the public preview page of the preprint, similar to what was done in [this example](https://jxiv.jst.go.jp/index.php/jxiv/user/setLocale/en_US?source=%2Findex.php%2Fjxiv%2Fpreprint%2Fview%2F397).

Please tell us if you agree?

With this scope above, the value for sponsored development would be 780 dollars.

**Comment by devinberg** [comment]
@diegoabadan This sounds about right as to what I would be looking for. Perhaps you can write a service contract and send it to me at director (at) engrxiv.org.

**Comment by pablovp86** [comment]
Available since [version 1.2.5](https://github.com/lepidus/authorVersion/releases/tag/v1.2.5).
